language: cpp

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "J8Y+eQD0p5YPOlhBEPFgpZzhRFjXC4phiiFtGV3JaYX34wxCsyyNhMStMqIZTBL4D9lQojfLgXODBDaqT1iSHDe1oonosnyYnGBIJElez247pjuNiSSvcAbYa9RQnwfHe8JFphQHViURbv0OfqpHHyAlHy5b8nrPYWG2xmHA5nY="

addons:
  coverity_scan:
    project:
      name: "bjorn/tiled"
      description: "A generic tile map editor"
    notification_email: bjorn@lindeijer.nl
    build_command_prepend: qmake
    build_command: make
    branch_pattern: coverity_scan

matrix:
    include:
        - compiler: gcc
        - compiler: clang
          env: QMAKESPEC=unsupported/linux-clang

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 50; fi
  - if [ "$CXX" = "g++" ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50; fi
  - sudo apt-get install -qq qt5-default qttools5-dev-tools zlib1g-dev cppcheck
  - qmake -version
  - Xvfb :1 &
  - xv -display :1 &
script:
  - export DISPLAY=:1
  - qmake
  - make
  - pushd tests/
  - qmake
  - make
  - for test in `find -executable -type f`; do pushd `dirname $test`; ./`basename $test`||exit 1; popd; done
  - popd
after_script: cppcheck --enable=all -q -Isrc/libtiled `git ls-files src/\*.cpp`
